<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Products\Validators\**" />
    <EmbeddedResource Remove="Features\Products\Validators\**" />
    <None Remove="Features\Products\Validators\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="MFO.Contracts" Version="1.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MFO.CatalogService.Domain\MFO.CatalogService.Domain.csproj" />
  </ItemGroup>

</Project>
